image: docker:latest

services:
  - docker:dind

stages:
  - build
  
before_script:
  - docker login -u anvibo -p $DOCKERHUB_PWD docker.io
  
build-18.04:
  stage: build
  script:
    - docker build --pull -t anvibo/baseimage -f 18.04/Dockerfile .
    - docker tag anvibo/baseimage anvibo/baseimage:18.04
    
    - docker push anvibo/baseimage:latest
    - docker push anvibo/baseimage:18.04